#!/usr/bin/env zsh
#   _________  _   _ ____   ____ 
#  |__  / ___|| | | |  _ \ / ___|
#    / /\___ \| |_| | |_) | |    
# _ / /_ ___) |  _  |  _ <| |___ 
#(_)____|____/|_| |_|_| \_\\____|
#
 
# /etc/zsh/zshrc ou ~/.zshrc
# Fichier de configuration principal de zsh, lu au lancement des shells interactifs
# (et non des shells d'interprétation de fichier)
# Formation Debian GNU/Linux par Alexis de Lattre
# http://formation-debian.via.ecp.fr/



#############
# Les alias #
#############

if [ -r ~/.zsh_alias ]
then
    source ~/.zsh_alias
fi


####################################
# Prompt et définition des touches #
####################################

if [ -r ~/.zsh_common ]
then
    source ~/.zsh_common
fi


#######
# Git #
#######

# if [ -r ~/.git-completion.zsh ]
# then
#     source ~/.git-completion.zsh    
# fi


############
# Portable #
############

export DELL="1"

# VIM
export VIMRUNTIME="/usr/share/vim/vim74"
export VIMRC="$HOME/Perso/work/env/vim"

