#!/usr/bin/env zsh
#   _________  _   _ ____   ____ 
#  |__  / ___|| | | |  _ \ / ___|
#    / /\___ \| |_| | |_) | |    
# _ / /_ ___) |  _  |  _ <| |___ 
#(_)____|____/|_| |_|_| \_\\____|
#
 
# /etc/zsh/zshrc ou ~/.zshrc
# Fichier de configuration principal de zsh, lu au lancement des shells interactifs
# (et non des shells d'interprétation de fichier)
# Formation Debian GNU/Linux par Alexis de Lattre
# http://formation-debian.via.ecp.fr/

#echo "** In  .zshrc **"


########
# Home #
########

# OWN
## see /etc/environment for CHROOT_WORKDIR="/home/greg/Greg/work/sequans/chroot/"

# VIM
export VIMRUNTIME="/usr/share/vim/vim74"
export VIMRC="$HOME/Greg/work/env/vim"

## PATH
for incr_path ( $HOME/Greg/work/env/bin )
do
    if [ -d $incr_path ]
    then
        if [ ! -z "$PATH" ]
        then
            path_status=`echo $PATH | grep "$incr_path"` >> /dev/null
            if [ -z "$path_status" ]
            then
                export PATH=${incr_path}:"${PATH}"
            fi
        else
            export PATH="${incr_path}"
        fi
    fi
    unset path_status
done


#############
# Les alias #
#############

if [ -r ~/.zsh_alias ]
then
    source ~/.zsh_alias
fi


####################################
# Prompt et définition des touches #
####################################

if [ -r ~/.zsh_common ]
then
    source ~/.zsh_common
fi


#######
# Git #
#######

# if [ -r ~/.git-completion.zsh ]
# then
#     source ~/.git-completion.zsh    
# fi

#echo "** Out .zshrc **"
